### PR TITLE
Refactored caching implementation

### PR DESCRIPTION
**Pull request by kaikreuzer**
Hey @spacemanspiff2007,

while reviewing, I thought it's probably easier to directly provide my comments as code, so I ended up heavily refactoring your PR. If you are fine with those changes, simply accept this PR against your branch (best by squash&merge) and they will turn up in your PR against openhab-core.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
Hey @kaikreuzer,
I'm really happy we are making some progress.

I thought listening to the User events from the registry was a nice idea to clean the cache once any user gets removed/modified.
What was your motivation to go with time based expiry instead?
I am concerned that this adds unnecessary overhead since the your clean algorithm runs every 10 requests which is multiple times per second.

Have you tried if you are getting cache hits? I tried the ``.toString`` method on the byte[] and suddenly I only got cache misses, but maybe I did something wrong.

**Comment by kaikreuzer** [comment]
> What was your motivation to go with time based expiry instead?

It is not "instead", it is in addition to it. Simply to not keep `UserSecurityContext`s indefinitely in memory, in case they aren't used.

> I am concerned that this adds unnecessary overhead since the your clean algorithm runs every 10 requests which is multiple times per second.

The overhead should be minimal and not noticeable, please test yourself.

> Have you tried if you are getting cache hits?

Yes, I have tested this. Please test yourself as well, just to assure yourself.

**Comment by spacemanspiff2007** [comment]
> It is not "instead", it is in addition to it. Simply to not keep `UserSecurityContext`s indefinitely in memory, in case they aren't used.

Ah - I see it now. I got confused by the merge view - sorry.

The key is salted and hashed - so this is pretty secure and should not be a problem to keep in memory.
The `UserSecurityContext` doesn't contain credentials, so what what are your concerns about having them in memory?

It's really great that you made the expiry time configurable via parameter! Should we allow 0 which subsequently will disable timely expiry?

I'll test the implementation this evening.

**Comment by spacemanspiff2007** [comment]
OH 2.5.3:
```
            |  dur   | per sec | median |  min   |  max   |  mean 
create item | 2.307s | 130.032 | 7.00ms | 6.00ms | 26.0ms | 7.69ms
update item | 2.245s | 133.623 | 7.00ms | 6.00ms | 17.0ms | 7.48ms
delete item | 1.691s | 177.400 | 5.00ms | 5.00ms | 18.0ms | 5.64ms

Bench item state update .... done!

                      |  dur   | per sec | median |  min   |  max   |  mean 
             rtt idle |  15.0s | 156.875 | 6.00ms | 6.00ms | 11.0ms | 6.37ms
       async rtt idle |  15.0s | 134.974 | 7.00ms | 7.00ms | 22.0ms | 7.41ms
      rtt load (+10x) |  15.0s |  18.234 | 54.0ms | 37.0ms | 77.0ms | 54.8ms
async rtt load (+10x) |  15.0s |  12.465 | 81.0ms | 67.0ms | 99.0ms | 80.2ms
```

This implementation:
```
            |  dur   | per sec | median |  min   |  max   |  mean 
create item | 2.547s | 117.779 | 8.00ms | 7.00ms | 25.0ms | 8.49ms
update item | 2.528s | 118.664 | 8.00ms | 7.00ms | 17.0ms | 8.43ms
delete item | 1.928s | 155.593 | 6.00ms | 5.00ms | 13.0ms | 6.43ms

Bench item state update .... done!

                      |  dur   | per sec | median |  min   |  max   |  mean 
             rtt idle |  15.0s | 153.658 | 6.00ms | 6.00ms | 13.0ms | 6.51ms
       async rtt idle |  15.0s | 134.410 | 7.00ms | 7.00ms | 15.0ms | 7.44ms
      rtt load (+10x) |  15.0s |  18.127 | 55.0ms | 42.0ms | 69.0ms | 55.2ms
async rtt load (+10x) |  15.0s |  12.302 | 80.0ms | 68.0ms | 0.106s | 81.3ms
```

The overhead seems to be at ~2%
I'd say this looks good!

**Comment by kaikreuzer** [comment]
> so what what are your concerns about having them in memory?

Well, they are still an object in itself that gives access to resources - not that critical, but a cleanup imho makes sense.

> Should we allow 0 which subsequently will disable timely expiry?

I don't see the need. People are free to put it to a large value.

> I'd say this looks good!

Excellent, happy to hear this! 🚀

**Pull request merged**
